quoted-strings: Fix crash with only-when-needed and escaped special characters
Prevent yamllint crash upon non-printable characters:

    $ yamllint -d 'rules: {quoted-strings: {required: only-when-needed}}' - <<<'key: "\u001b"'
    …
    yaml.reader.ReaderError: unacceptable character #x001b: special characters are not allowed
      in "<unicode string>", position 5

Accept escaped special characters in double quoted strings (`key:
"\u001b"`). But still throw exceptions for unescaped (embedded) special
characters, whether or not quotes are present.

When checking whether quotes are needed, assume that double-quoted
strings containing special characters have already been escaped (and
claim the quotes are in fact needed).

Fixes https://github.com/adrienverge/yamllint/issues/700